package io.github.chelseakr.ctdlvalidate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.Predicate;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * The one place this port is allowed to disagree with the pinned reference, held to exactly what it
 * is allowed to disagree about.
 *
 * <p>{@code parity/fixtures/} is byte equality and stays that way. {@code parity/ahead/fixtures/}
 * holds the payloads where this port answers differently on purpose, because the reference release
 * the parity corpus is pinned to predates three dispositions. {@code parity/ahead/reference/}
 * records what that pinned release really says, generated by the same script and checked by the
 * same CI job as {@code parity/expected/}, so the baseline is measured rather than remembered.
 *
 * <p>No Java-side golden file exists here, deliberately: freezing this implementation's own output
 * would be the self-comparison ADR 0003 rules out. What is asserted instead is the <em>shape</em>
 * of the divergence. Every finding is either identical to the reference's, or one declared
 * restatement, or one declared withdrawal, and every declared disposition is gated on a predicate
 * read out of the vendored snapshot, so a disagreement can never be justified by anything but the
 * schema. The port may never <em>add</em> a finding the reference does not have.
 *
 * <p>This suite is also how the divergence ends. When the pin is bumped to a release carrying these
 * fixes, the reference will stop disagreeing and {@link #stillDisagreesWithThePinnedReference}
 * fails, which is the instruction to move the affected fixtures into {@code parity/fixtures/} and
 * delete the entry. See {@code docs/adr/0004-the-port-may-lead-the-pinned-reference.md}.
 */
class AheadOfReferenceTest {

  private static final Path ROOT =
      Path.of(System.getProperty("ctdlvalidate.repoRoot", System.getProperty("user.dir")));
  private static final Path FIXTURES = ROOT.resolve("parity/ahead/fixtures");
  private static final Path REFERENCE = ROOT.resolve("parity/ahead/reference");

  private static final ObjectMapper MAPPER = new ObjectMapper();

  /** A withdrawal: the port reports nothing where the reference reported a finding. */
  private static final String WITHDRAWN = null;

  /**
   * One way this port is permitted to answer differently from the pinned reference.
   *
   * @param referenceCode the code the pinned reference emits
   * @param referenceSeverity the severity the pinned reference emits
   * @param portCode the code this port emits instead, or {@link #WITHDRAWN} for no finding at all
   * @param portSeverity the severity this port emits instead, or {@link #WITHDRAWN}
   * @param appliesTo which properties may be disposed of this way, read out of the vendored
   *     snapshot rather than listed, so refreshing the schema refreshes the permission
   * @param why the disposition, for a failure message that says what was expected
   */
  private record Disposition(
      String referenceCode,
      String referenceSeverity,
      String portCode,
      String portSeverity,
      Predicate<String> appliesTo,
      String why) {

    boolean withdraws() {
      return portCode == null;
    }
  }

  /**
   * Every disagreement this port is allowed to have with the pinned release, and nothing else.
   *
   * <p>Each predicate is derived from the vendored snapshot on every run. That is what stops this
   * table from being a licence: a disposition can only reach a property the published schema
   * actually declares the way the disposition claims it does.
   */
  private static List<Disposition> dispositions() {
    SchemaIndex schema = SchemaLoader.load();
    return List.of(
        new Disposition(
            "RANGE_VIOLATION",
            "ERROR",
            "CONCEPT_RANGE_CONFLICT",
            "INFO",
            prop -> schema.schemeBoundConceptProperties().contains(prop),
            "a scheme-bound concept reference encoded as a CredentialAlignmentObject"),
        new Disposition(
            "RANGE_VIOLATION",
            "ERROR",
            "VERSION_RANGE_CONFLICT",
            "INFO",
            prop ->
                SchemaIndex.VERSION_PROPERTIES.contains(prop)
                    && !schema.domainOnlyClasses(prop).isEmpty(),
            "a version property whose declared range is a strict subset of its own domain"),
        new Disposition(
            "RANGE_VIOLATION",
            "ERROR",
            WITHDRAWN,
            WITHDRAWN,
            prop -> schema.property(prop) != null && schema.property(prop).rangeIsUniversal(),
            "a declared range of rdfs:Resource, which admits every entity there is"),
        new Disposition(
            "INVERSE_MISMATCH",
            "ERROR",
            WITHDRAWN,
            WITHDRAWN,
            prop -> schema.property(prop) != null && schema.property(prop).inverse() != null,
            "a back-reference written as a nested object carrying the referenced @id"));
  }

  /**
   * How many disagreements with the pinned release this port declares.
   *
   * <p>Exposed for {@code PublishedFiguresTest}, which holds the README and CONTRIBUTING to this
   * number rather than to a count someone typed. Derived from the table above on every call.
   */
  static int declaredDispositions() {
    return dispositions().size();
  }

  /**
   * How many declared dispositions take an ERROR the pinned release raises and either withdraw it
   * or restate it below ERROR.
   *
   * <p>Also for {@code PublishedFiguresTest}: the README's claim about which direction the
   * divergence runs in is a property of the table, not a sentence to keep in step by hand.
   */
  static int dispositionsThatRemoveAnError() {
    int removing = 0;
    for (Disposition disposition : dispositions()) {
      if ("ERROR".equals(disposition.referenceSeverity())
          && !"ERROR".equals(disposition.portSeverity())) {
        removing++;
      }
    }
    return removing;
  }

  static Stream<String> fixtureNames() throws IOException {
    try (Stream<Path> files = Files.list(FIXTURES)) {
      return files
          .map(path -> String.valueOf(path.getFileName()))
          .filter(name -> name.endsWith(".json"))
          .sorted()
          .toList()
          .stream();
    }
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtureNames")
  @DisplayName(
      "the port still disagrees with the pinned reference, which is why this corpus exists")
  void stillDisagreesWithThePinnedReference(String name) throws IOException {
    assertNotEquals(
        referenceDocument(name).toString(),
        portDocument(name).toString(),
        () ->
            "The pinned reference now agrees with this port on "
                + name
                + ". The divergence this corpus records is over: move the fixture into"
                + " parity/fixtures/, regenerate parity/expected/, and delete the parity/ahead/"
                + " entry rather than leaving a comparison here that no longer compares anything.");
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtureNames")
  @DisplayName("every disagreement is a declared disposition and nothing else")
  void everyDisagreementIsDeclared(String name) throws IOException {
    JsonNode reference = referenceDocument(name);
    JsonNode port = portDocument(name);

    assertTrue(
        disagreementsBetween(name, reference, port) > 0,
        name + ": nothing was disposed of, so this fixture belongs in parity/fixtures/");
    assertEquals(
        1, reference.get("exit_code").asInt(), name + ": the reference was expected to fail this");

    // Every disposition is non-gating, so disposing of one strictly reduces the
    // errors. Asserting the port exits 0 outright would be wrong: a fixture may
    // carry an unrelated ERROR that both sides agree on, and universal_range
    // does -- owl:sameAs raises a DOMAIN_VIOLATION on both sides, which this
    // port has deliberately not disposed of. See the README limits.
    int referenceErrors = errorsIn(reference);
    int portErrors = errorsIn(port);
    assertTrue(
        portErrors < referenceErrors,
        () ->
            name
                + ": the dispositions removed no ERROR ("
                + referenceErrors
                + " before, "
                + portErrors
                + " after), so nothing here is non-gating");
    assertEquals(
        portErrors > 0 ? 1 : 0,
        port.get("exit_code").asInt(),
        name + ": the port's exit code disagrees with its own ERROR count");
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtureNames")
  @DisplayName("the comparison notices a divergence wider than the declared dispositions")
  void theComparisonItselfHasBeenBroken(String name) throws IOException {
    // A check nobody has watched fail is a check you are trusting on faith. Each
    // corruption below is a way the dispositions could quietly widen: disposing of
    // a finding that was never a range violation, disposing of one at a severity
    // no disposition covers, disposing of one on a property the snapshot does not
    // mark, and dropping a finding nothing permits dropping.
    JsonNode port = portDocument(name);
    Map<String, String> corruptions =
        new java.util.LinkedHashMap<>(
            Map.of(
                "code", "DOMAIN_VIOLATION",
                "severity", "WARNING",
                "property", "ceterms:classification"));

    // entity and value are only compared where the port restated the finding.
    // A withdrawal has no counterpart to compare them against, so requiring the
    // comparison to notice them there would be asserting something this suite
    // does not check. A fixture whose findings all came back restated does check
    // them, and is held to it.
    if (portDocument(name).get("findings").size()
        == referenceDocument(name).get("findings").size()) {
      corruptions.put("value", "a value the port never reported");
      corruptions.put("entity", "an entity the port never reported");
    }

    for (Map.Entry<String, String> corruption : corruptions.entrySet()) {
      JsonNode reference =
          corruptFirstDisagreement(
              referenceDocument(name), port, corruption.getKey(), corruption.getValue());
      assertThrows(
          AssertionError.class,
          () -> disagreementsBetween(name, reference, port),
          "the comparison waved through a changed " + corruption.getKey());
    }

    // A finding the reference does not have at all: the port may never add one.
    //
    // The finding removed has to be one the port actually reports. Removing a
    // withdrawn finding is undetectable by construction and rightly so: the port
    // reports nothing for it either way, so its absence from the reference
    // changes nothing to compare. Removing one the port restates or repeats
    // verbatim is the case that must fail, and is the one taken here.
    JsonNode shortened = referenceDocument(name);
    ArrayNode findings = (ArrayNode) shortened.get("findings");
    int removable = indexOfFindingThePortReports(findings, port);
    assertNotEquals(-1, removable, name + ": no finding the port reports, so nothing to remove");
    findings.remove(removable);
    assertThrows(
        AssertionError.class,
        () -> disagreementsBetween(name, shortened, port),
        "the comparison waved through a finding the reference never reported");
  }

  /**
   * The reference document with one field of its first disposed-of finding changed.
   *
   * <p>Asserts the corruption actually changed something. A corruption that lands on nothing
   * produces a green test that looks like a proof.
   */
  private static JsonNode corruptFirstDisagreement(
      JsonNode reference, JsonNode port, String field, String replacement) {
    Set<String> portFindings = new TreeSet<>();
    for (JsonNode finding : port.get("findings")) {
      portFindings.add(finding.toString());
    }
    for (JsonNode candidate : reference.get("findings")) {
      ObjectNode finding = (ObjectNode) candidate;
      if (portFindings.contains(finding.toString())) {
        continue; // restated verbatim by the port; not a disagreement
      }
      assertNotEquals(replacement, finding.get(field).asText(), "the corruption changed nothing");
      finding.put(field, replacement);
      return reference;
    }
    throw new AssertionError("no disposed-of finding to corrupt");
  }

  /**
   * How many findings the port disposed of, failing if it did anything else to any of them.
   *
   * <p>Walks both ordered lists together. A finding the port restates verbatim consumes one of
   * each; a declared restatement consumes one of each and counts; a declared withdrawal consumes
   * the reference's alone and counts. Anything else, including a finding the port has and the
   * reference does not, fails.
   *
   * @return the number of findings disposed of
   */
  private static int disagreementsBetween(String name, JsonNode reference, JsonNode port) {
    List<Disposition> allowed = dispositions();
    JsonNode portFindings = port.get("findings");

    int disposed = 0;
    int portIndex = 0;
    for (JsonNode expected : reference.get("findings")) {
      JsonNode actual = portIndex < portFindings.size() ? portFindings.get(portIndex) : null;
      if (actual != null && expected.equals(actual)) {
        portIndex++;
        continue;
      }

      String property = text(expected, "property");
      List<String> tried = new ArrayList<>();
      Disposition matched = null;
      for (Disposition disposition : allowed) {
        if (!disposition.referenceCode().equals(text(expected, "code"))
            || !disposition.referenceSeverity().equals(text(expected, "severity"))) {
          continue;
        }
        if (!disposition.appliesTo().test(property)) {
          tried.add(disposition.why() + " (the snapshot does not mark " + property + ")");
          continue;
        }
        if (disposition.withdraws()) {
          matched = disposition;
          break;
        }
        if (actual != null
            && disposition.portCode().equals(text(actual, "code"))
            && disposition.portSeverity().equals(text(actual, "severity"))) {
          // The finding still points at the same thing; only the ruling changed.
          for (String field : List.of("entity", "property", "value")) {
            assertEquals(
                text(expected, field),
                text(actual, field),
                name + ": the restatement moved the finding's " + field);
          }
          matched = disposition;
          portIndex++;
          break;
        }
        tried.add(
            disposition.why()
                + " (the port did not restate it as "
                + disposition.portCode()
                + "/"
                + disposition.portSeverity()
                + ")");
      }

      final List<String> considered = tried;
      assertTrue(
          matched != null,
          () ->
              name
                  + ": undeclared disagreement on "
                  + text(expected, "code")
                  + "/"
                  + text(expected, "severity")
                  + " for "
                  + property
                  + ". Considered: "
                  + (considered.isEmpty()
                      ? "no disposition has that reference code and severity"
                      : considered));
      disposed++;
    }

    assertEquals(
        portFindings.size(),
        portIndex,
        name
            + ": the port reported "
            + (portFindings.size() - portIndex)
            + " finding(s) the reference does not have. A disposition may restate or withdraw a"
            + " finding, never invent one.");
    return disposed;
  }

  /**
   * The index of a reference finding whose removal the comparison must notice.
   *
   * <p>Either one the port repeats verbatim, or, where the port restated every disagreement, any of
   * them: removing one then leaves the port holding a finding the reference does not have, which is
   * the invariant under test.
   */
  private static int indexOfFindingThePortReports(ArrayNode referenceFindings, JsonNode port) {
    JsonNode portFindings = port.get("findings");
    Set<String> reported = new TreeSet<>();
    for (JsonNode finding : portFindings) {
      reported.add(finding.toString());
    }
    for (int i = 0; i < referenceFindings.size(); i++) {
      if (reported.contains(referenceFindings.get(i).toString())) {
        return i;
      }
    }
    return referenceFindings.size() == portFindings.size() && referenceFindings.size() > 0 ? 0 : -1;
  }

  /** How many ERROR findings a rendered document carries. */
  private static int errorsIn(JsonNode document) {
    int errors = 0;
    for (JsonNode finding : document.get("findings")) {
      if ("ERROR".equals(text(finding, "severity"))) {
        errors++;
      }
    }
    return errors;
  }

  /** A field's text, or a marker no real value collides with when the field is missing. */
  private static String text(JsonNode finding, String field) {
    JsonNode value = finding.get(field);
    return value == null ? "<absent>" : value.asText();
  }

  @Test
  @DisplayName("every declared disposition is exercised by some fixture")
  void everyDispositionIsExercised() throws IOException {
    // A disposition nothing reaches is a permission nobody is checking. If one
    // stops being exercised, either the corpus lost a fixture or the disposition
    // is dead and should be deleted rather than left standing.
    Set<String> exercised = new TreeSet<>();
    for (String name : fixtureNames().toList()) {
      Set<String> portFindings = new TreeSet<>();
      for (JsonNode finding : portDocument(name).get("findings")) {
        portFindings.add(finding.toString());
      }
      for (JsonNode expected : referenceDocument(name).get("findings")) {
        if (portFindings.contains(expected.toString())) {
          continue;
        }
        for (Disposition disposition : dispositions()) {
          if (disposition.referenceCode().equals(text(expected, "code"))
              && disposition.appliesTo().test(text(expected, "property"))) {
            exercised.add(disposition.why());
          }
        }
      }
    }
    Set<String> declared = new TreeSet<>();
    for (Disposition disposition : dispositions()) {
      declared.add(disposition.why());
    }
    assertEquals(declared, exercised, "a declared disposition no fixture reaches");
  }

  @Test
  @DisplayName("the corpus is non-empty and every fixture has a recorded reference document")
  void corpusIsComplete() throws IOException {
    Set<String> fixtures = new TreeSet<>(fixtureNames().toList());
    Set<String> recorded = new TreeSet<>();
    try (Stream<Path> files = Files.list(REFERENCE)) {
      files
          .map(path -> String.valueOf(path.getFileName()))
          .filter(name -> name.endsWith(".json"))
          .forEach(recorded::add);
    }
    assertFalse(fixtures.isEmpty(), "the ahead corpus is empty");
    assertEquals(
        fixtures,
        recorded,
        "every ahead fixture needs a reference document; run tools/generate_expectations.py");
  }

  /** What this Java implementation reports, parsed back for structural comparison. */
  static JsonNode portDocument(String name) throws IOException {
    return MAPPER.readTree(ParityDocument.render(MAPPER.readTree(FIXTURES.resolve(name).toFile())));
  }

  private static JsonNode referenceDocument(String name) throws IOException {
    return MAPPER.readTree(Files.readString(REFERENCE.resolve(name), StandardCharsets.UTF_8));
  }
}
