package io.github.chelseakr.ctdlvalidate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Stream;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * The one place this port is allowed to disagree with the pinned reference, held to exactly what it
 * is allowed to disagree about.
 *
 * <p>{@code parity/fixtures/} is byte equality and stays that way. {@code parity/ahead/fixtures/}
 * holds the payloads where this port answers differently on purpose, because the reference release
 * the parity corpus is pinned to predates the concept-range disposition. {@code
 * parity/ahead/reference/} records what that pinned release really says, generated by the same
 * script and checked by the same CI job as {@code parity/expected/}, so the baseline is measured
 * rather than remembered.
 *
 * <p>No Java-side golden file exists here, deliberately: freezing this implementation's own output
 * would be the self-comparison ADR 0003 rules out. What is asserted instead is the <em>shape</em>
 * of the divergence — every finding is either identical to the reference's or is one specific,
 * declared substitution — so widening the disposition by even one extra finding fails the build.
 *
 * <p>This suite is also how the divergence ends. When the pin is bumped to a release carrying the
 * fix, the reference will stop disagreeing and {@link #stillDisagreesWithThePinnedReference} fails,
 * which is the instruction to move these fixtures into {@code parity/fixtures/} and delete this
 * corpus. See {@code docs/adr/0004-the-port-may-lead-the-pinned-reference.md}.
 */
class AheadOfReferenceTest {

  private static final Path ROOT =
      Path.of(System.getProperty("ctdlvalidate.repoRoot", System.getProperty("user.dir")));
  private static final Path FIXTURES = ROOT.resolve("parity/ahead/fixtures");
  private static final Path REFERENCE = ROOT.resolve("parity/ahead/reference");

  private static final ObjectMapper MAPPER = new ObjectMapper();

  /** The substitution this port is permitted to make, and nothing else. */
  private static final String REFERENCE_CODE = "RANGE_VIOLATION";

  private static final String PORT_CODE = "CONCEPT_RANGE_CONFLICT";

  static Stream<String> fixtureNames() throws IOException {
    try (Stream<Path> files = Files.list(FIXTURES)) {
      return files
          .map(path -> String.valueOf(path.getFileName()))
          .filter(name -> name.endsWith(".json"))
          .sorted()
          .toList()
          .stream();
    }
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtureNames")
  @DisplayName(
      "the port still disagrees with the pinned reference, which is why this corpus exists")
  void stillDisagreesWithThePinnedReference(String name) throws IOException {
    assertNotEquals(
        referenceDocument(name).toString(),
        portDocument(name).toString(),
        () ->
            "The pinned reference now agrees with this port on "
                + name
                + ". The divergence this corpus records is over: move the fixture into"
                + " parity/fixtures/, regenerate parity/expected/, and delete the parity/ahead/"
                + " entry rather than leaving a comparison here that no longer compares anything.");
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtureNames")
  @DisplayName("every disagreement is the concept-range disposition and nothing else")
  void everyDisagreementIsTheDeclaredSubstitution(String name) throws IOException {
    JsonNode reference = referenceDocument(name);
    JsonNode port = portDocument(name);

    assertTrue(
        substitutionsBetween(name, reference, port) > 0,
        name + ": nothing was substituted, so this fixture belongs in parity/fixtures/");
    assertEquals(
        0,
        port.get("exit_code").asInt(),
        name + ": an INFO disposition must not gate the exit code");
    assertEquals(
        1, reference.get("exit_code").asInt(), name + ": the reference was expected to fail this");
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("fixtureNames")
  @DisplayName("the comparison notices a divergence wider than the disposition")
  void theComparisonItselfHasBeenBroken(String name) throws IOException {
    // A check nobody has watched fail is a check you are trusting on faith. Each
    // corruption below is a way the disposition could quietly widen: swallowing a
    // finding that was never a range violation, and swallowing one about a
    // different value. Both must be rejected, or this suite is waving through
    // exactly what it exists to bound.
    JsonNode port = portDocument(name);
    Map<String, String> corruptions =
        Map.of(
            "code", "DOMAIN_VIOLATION",
            "severity", "WARNING",
            "value", "a value the port never reported",
            "property", "ceterms:classification");
    for (Map.Entry<String, String> corruption : corruptions.entrySet()) {
      JsonNode reference =
          corruptFirstSubstitution(
              referenceDocument(name), port, corruption.getKey(), corruption.getValue());
      assertThrows(
          AssertionError.class,
          () -> substitutionsBetween(name, reference, port),
          "the comparison waved through a changed " + corruption.getKey());
    }

    JsonNode shortened = referenceDocument(name);
    ((ArrayNode) shortened.get("findings")).remove(0);
    assertThrows(
        AssertionError.class,
        () -> substitutionsBetween(name, shortened, port),
        "the comparison waved through a dropped finding");
  }

  /** The reference document with one field of its first restated finding changed. */
  private static JsonNode corruptFirstSubstitution(
      JsonNode reference, JsonNode port, String field, String replacement) {
    JsonNode findings = reference.get("findings");
    for (int i = 0; i < findings.size(); i++) {
      ObjectNode finding = (ObjectNode) findings.get(i);
      if (finding.equals(port.get("findings").get(i))) {
        continue;
      }
      assertNotEquals(replacement, finding.get(field).asText(), "the corruption changed nothing");
      finding.put(field, replacement);
      return reference;
    }
    throw new AssertionError("no substituted finding to corrupt");
  }

  /**
   * How many findings the port restated, failing if it did anything else to any of them.
   *
   * @return the number of findings where the port and the reference disagree
   */
  private static int substitutionsBetween(String name, JsonNode reference, JsonNode port) {
    JsonNode referenceFindings = reference.get("findings");
    JsonNode portFindings = port.get("findings");
    assertEquals(
        referenceFindings.size(),
        portFindings.size(),
        name + ": the disposition may restate a finding, never add or drop one");

    int substituted = 0;
    for (int i = 0; i < referenceFindings.size(); i++) {
      JsonNode expected = referenceFindings.get(i);
      JsonNode actual = portFindings.get(i);
      if (expected.equals(actual)) {
        continue;
      }
      substituted++;
      assertEquals(
          REFERENCE_CODE, text(expected, "code"), name + ": the reference was not a range error");
      assertEquals("ERROR", text(expected, "severity"), name + ": the reference was not an ERROR");
      assertEquals(PORT_CODE, text(actual, "code"), name + ": unexpected port code");
      assertEquals("INFO", text(actual, "severity"), name + ": the disposition must be INFO");

      // The finding still points at the same thing; only the ruling changed.
      for (String field : List.of("entity", "property", "value")) {
        assertEquals(
            text(expected, field),
            text(actual, field),
            name + ": the substitution moved the finding's " + field);
      }

      // And it only reaches properties the vendored snapshot actually marks, so
      // a substitution can never be justified by anything but the schema.
      String property = text(actual, "property");
      assertTrue(
          SchemaLoader.load().schemeBoundConceptProperties().contains(property),
          name + ": " + property + " is not scheme-bound in the snapshot");
    }
    return substituted;
  }

  /** A field's text, or a marker no real value collides with when the field is missing. */
  private static String text(JsonNode finding, String field) {
    JsonNode value = finding.get(field);
    return value == null ? "<absent>" : value.asText();
  }

  @Test
  @DisplayName("the corpus is non-empty and every fixture has a recorded reference document")
  void corpusIsComplete() throws IOException {
    Set<String> fixtures = new TreeSet<>(fixtureNames().toList());
    Set<String> recorded = new TreeSet<>();
    try (Stream<Path> files = Files.list(REFERENCE)) {
      files
          .map(path -> String.valueOf(path.getFileName()))
          .filter(name -> name.endsWith(".json"))
          .forEach(recorded::add);
    }
    assertFalse(fixtures.isEmpty(), "the ahead corpus is empty");
    assertEquals(
        fixtures,
        recorded,
        "every ahead fixture needs a reference document; run tools/generate_expectations.py");
  }

  /** What this Java implementation reports, parsed back for structural comparison. */
  static JsonNode portDocument(String name) throws IOException {
    return MAPPER.readTree(ParityDocument.render(MAPPER.readTree(FIXTURES.resolve(name).toFile())));
  }

  private static JsonNode referenceDocument(String name) throws IOException {
    return MAPPER.readTree(Files.readString(REFERENCE.resolve(name), StandardCharsets.UTF_8));
  }
}
